### ISSUE TITLE
An typescript error in 5.1.0

### ISSUE THREAD

**Issue by hibi66** [ecomfe/awesome-echarts#32]
Failed to compile.
*****node_modules/echarts/types/dist/echarts.d.ts
TypeScript error in *****node_modules/echarts/types/dist/echarts.d.ts(6391,13):
Type expected. TS1110
6389 | $vars: string[];
6390 | } & {
> 6391 | [key in `${ComponentMainType}Index`]: number;
| ^
6392 | } & {
6393 | [key in string]: unknown;
6394 | };
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by junchaohu** [comment]
Same issue here, wish for resolve.

**Comment by pissang** [comment]
Will be fixed in 5.1.1

**Comment by tonyabracadabra** [comment]
> Will be fixed in 5.1.1

looks like it is not solved yet? I am using version 5.1.2

**Comment by Ovilia** [comment]
Please open an issue in apache/echarts if this remains to be a problem.
