### ISSUE TITLE
ECharts Gallery   can't  access

### ISSUE THREAD

**Issue by lifeisattrip** [ecomfe/awesome-echarts#33]
ECharts Gallery   can't  access

**Comment by plainheart** [comment]
Hi, gallery.echartsjs.com is not used anymore because of the branding issue.
Now you could access the new website: https://www.makeapie.com

**Comment by Mrjzf** [comment]
@plainheart https://www.makeapie.com/  can't access

**Comment by plainheart** [comment]
See apache/echarts#16471
