### ISSUE TITLE
An incorrect link in the extension section (liquidfill)

### ISSUE THREAD

**Issue by iydon** [ecomfe/awesome-echarts#36]
https://github.com/ecomfe/awesome-echarts/blob/9027bce29a0599912d5ec2ef77480aba6022bcf2/README.md#L75

```markdown
[liquidfill 水球图](https://github.com/ecomfe/echarts-liquidfill)
```

**Comment by plainheart** [comment]
You are welcome to open a PR to correct it. Thanks!

**Comment by Ovilia** [comment]
Fixed
