### ISSUE TITLE
ECharts Gallery can't access

### ISSUE THREAD

**Issue by fivefog** [ecomfe/awesome-echarts#37]
![image](https://user-images.githubusercontent.com/53244212/153179363-343aa9c3-05e9-42c9-888f-dd6ab38559b5.png)

**Comment by plainheart** [comment]
See https://github.com/apache/echarts/issues/16471

**Comment by yangxianpei** [comment]
说真的 就用到百度唯一的东西 他还给关了

**Comment by glzcc** [comment]
> 说真的 就用到百度唯一的东西 他还给关了

哈哈

**Comment by xingyuehaiqing** [comment]
http://ppchart.com
这个可以
