### ISSUE TITLE
link need update

### ISSUE THREAD

**Issue by lloydzhou** [ecomfe/awesome-echarts#43]
![image](https://user-images.githubusercontent.com/1826685/185146394-4728e792-fcdf-4c3a-8115-3da0c1c995fd.png)

![image](https://user-images.githubusercontent.com/1826685/185146568-5342b75b-0bdf-423b-98d1-f3cdd4a75a54.png)

https://github.com/lulucut/echarts-middleware

**Comment by Ovilia** [comment]
Can you make a PR, please?
